name: first_try
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  flutter_launcher_icons: ^0.13.1


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/games_data.json
  - assets/png/
  fonts:
    - family: ConcertOne
      fonts:
        - asset: assets/fonts/ConcertOne-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.png



 
